PKTTYPE_LOGIN_VERSION = 0x11
PKTTYPE_LOGIN_CREATE = 0x13
PKTTYPE_LOGIN_AUTHENTICATE = 0x14
PKTTYPE_LOGIN_CHARACTER_CREATE = 0x17
PKTTYPE_LOGIN_CHARACTER_SELECT = 0x16

PKTTYPE_GAMESERVER_LOGIN = 0x1f
PKTTYPE_WELCOME = 0x10
PKTTYPE_TRANSFER_READY = 0x1d
PKTTYPE_OPEN_DOOR = 0x2D

PKTTYPE_ENT_INCREMENTAL_UPDATE = 0x7
PKTTYPE_ENT_POWER_CAST = 0x9
PKTTYPE_ENT_FULL_UPDATE = 0x8

PKTTYPE_REQUEST_RESPAWN      = 0x77
PKTTYPE_RESPAWN_COMPLETE     = 0x80
PKTTYPE_CHAR_REGEN           = 0x78
PKTTYPE_RESPAWN_ACK          = 0x82

PKTTYPE_BUFF_TICK_DOT = 0x79
PKTTYPE_ENT_DESTROY = 0x0D
PKTTYPE_EMOTE_BEGIN = 0x7E
PKTTYPE_KEYBINDS = 0xBC